# Generated by Django 6.1.1 on 2026-09-15 00:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mairie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citoyen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=150)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=200)),
                ('nationalite', models.CharField(default='Malienne', max_length=100)),
                ('profession', models.CharField(blank=True, max_length=150)),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('numero_piece_identite', models.CharField(blank=True, max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('mairie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citoyens', to='mairie.mairie')),
            ],
            options={
                'verbose_name': 'Citoyen',
                'verbose_name_plural': 'Citoyens',
                'ordering': ['nom', 'prenom'],
                'indexes': [models.Index(fields=['nom', 'prenom'], name='citoyens_ci_nom_e64652_idx'), models.Index(fields=['date_naissance'], name='citoyens_ci_date_na_bff9da_idx'), models.Index(fields=['numero_piece_identite'], name='citoyens_ci_numero__16a495_idx')],
            },
        ),
    ]
