# Generated by Django 6.1.1 on 2026-09-15 00:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mairie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50)),
                ('type_acte', models.CharField(choices=[('NAISSANCE', 'Naissance'), ('MARIAGE', 'Mariage'), ('DECES', 'Décès')], max_length=20)),
                ('annee', models.PositiveIntegerField()),
                ('date_acte', models.DateField()),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=20)),
                ('observation', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actes_crees', to=settings.AUTH_USER_MODEL)),
                ('mairie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actes', to='mairie.mairie')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actes_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acte',
                'verbose_name_plural': 'Actes',
                'ordering': ['-date_acte', '-date_creation'],
                'indexes': [models.Index(fields=['mairie', 'type_acte'], name='etat_civil__mairie__cb0b95_idx'), models.Index(fields=['mairie', 'annee'], name='etat_civil__mairie__3cc0cb_idx'), models.Index(fields=['numero'], name='etat_civil__numero_925bc9_idx'), models.Index(fields=['date_acte'], name='etat_civil__date_ac_ab3f7e_idx')],
                'constraints': [models.UniqueConstraint(fields=('mairie', 'numero'), name='unique_numero_acte_par_mairie')],
            },
        ),
    ]
