# Generated by Django 6.1.1 on 2026-09-15 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citoyens', '0001_initial'),
        ('etat_civil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_deces', models.DateField()),
                ('heure_deces', models.TimeField(blank=True, null=True)),
                ('lieu_deces', models.CharField(max_length=200)),
                ('cause_deces', models.CharField(blank=True, max_length=250)),
                ('declarant_nom', models.CharField(blank=True, max_length=200)),
                ('declarant_qualite', models.CharField(blank=True, max_length=150)),
                ('observations', models.TextField(blank=True)),
                ('acte', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='deces', to='etat_civil.acte')),
                ('defunt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deces', to='citoyens.citoyen')),
            ],
            options={
                'verbose_name': 'Acte de décès',
                'verbose_name_plural': 'Actes de décès',
            },
        ),
    ]
